/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import Model.KhuyenMaii;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.KhuyenMaii;
import Sevice.KhuyenMaiService;

/**
 *
 * @author LE DINH LINH
 */
public class KhuyenMaiPanell extends javax.swing.JPanel {

    /**
     * Creates new form KhuyenMaiPanell
     */
    private KhuyenMaiService khuyenMaiService;

    public KhuyenMaiPanell() {
        initComponents();
        khuyenMaiService = new KhuyenMaiService();
        loadDataToTable();
    }

    private void loadDataToTable() {
        List<KhuyenMaii> danhSachKhuyenMai = khuyenMaiService.layTatCaKhuyenMai();

        DefaultTableModel model = (DefaultTableModel) tblKM.getModel();
        model.setRowCount(0);

        for (KhuyenMaii km : danhSachKhuyenMai) {
            Object[] row = {km.getMaKM(), km.getPhanTramGiamGia(), km.getSoLuong(), km.getNgayBatDau(), km.getNgayKetThuc()};
            model.addRow(row);
        }
    }

    private boolean validateInput(String phanTramGiam, String soLuong, Date ngayBatDau, Date ngayKetThuc) {
        if (phanTramGiam.isEmpty() || soLuong.isEmpty() || ngayBatDau == null || ngayKetThuc == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin");
            return false;
        }

        try {
            int phanTram = Integer.parseInt(phanTramGiam);
            int soLuongKM = Integer.parseInt(soLuong);

            if (phanTram < 1 || phanTram > 100) {
                JOptionPane.showMessageDialog(this, "Phần trăm giảm giá phải nằm trong khoảng từ 1 đến 100");
                return false;
            }

            if (soLuongKM < 0) {
                JOptionPane.showMessageDialog(this, "Số lượng không được âm");
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Phần trăm giảm và số lượng phải là số nguyên");
            return false;
        }

        if (ngayBatDau.after(ngayKetThuc)) {
            JOptionPane.showMessageDialog(this, "Ngày kết thúc phải sau ngày bắt đầu");
            return false;
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTimTheoma = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKM = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtphantramgiam = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtsoluong = new javax.swing.JTextField();
        ngaybatdau = new com.toedter.calendar.JDateChooser();
        ngayketthuc = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnTim = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnthem = new javax.swing.JButton();
        btnlammoi = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Tìm kiếm:");

        tblKM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khuyến mãi", "% Giảm", "Số lượng", "Ngày bắt đầu", "Ngày kết thúc"
            }
        ));
        tblKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKMMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKM);

        jLabel2.setText("Giảm %");

        jLabel3.setText("Số lượng");

        jLabel4.setText("Ngày Bắt Đầu ");

        jLabel5.setText("Ngày kết thúc");

        btnTim.setBackground(new java.awt.Color(0, 0, 0));
        btnTim.setForeground(new java.awt.Color(255, 255, 255));
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnsua.setBackground(new java.awt.Color(0, 0, 0));
        btnsua.setForeground(new java.awt.Color(255, 255, 255));
        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnthem.setBackground(new java.awt.Color(0, 0, 0));
        btnthem.setForeground(new java.awt.Color(255, 255, 255));
        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnlammoi.setBackground(new java.awt.Color(0, 0, 0));
        btnlammoi.setForeground(new java.awt.Color(255, 255, 255));
        btnlammoi.setText("Làm Mới");
        btnlammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlammoiActionPerformed(evt);
            }
        });

        btnxoa.setBackground(new java.awt.Color(0, 0, 0));
        btnxoa.setForeground(new java.awt.Color(255, 255, 255));
        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(txtTimTheoma, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnTim)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ngaybatdau, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                .addComponent(txtphantramgiam, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtsoluong, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ngayketthuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(27, 44, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnthem)
                            .addComponent(btnxoa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnlammoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnsua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(62, 62, 62))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimTheoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnTim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(txtphantramgiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ngaybatdau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ngayketthuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnxoa, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(btnlammoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(150, 150, 150))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        String maKM = txtTimTheoma.getText();
        boolean searchResult = searchByMaKhuyenMai(maKM);

        if (searchResult) {
            JOptionPane.showMessageDialog(this, "Tìm mã khuyến mãi thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy mã khuyến mãi");
        }
    }

    private boolean searchByMaKhuyenMai(String maKM) {
        KhuyenMaii khuyenMai = khuyenMaiService.timKhuyenMaiTheoMa(maKM);

        DefaultTableModel model = (DefaultTableModel) tblKM.getModel();
        model.setRowCount(0);

        if (khuyenMai != null) {
            Object[] row = {khuyenMai.getMaKM(), khuyenMai.getPhanTramGiamGia(), khuyenMai.getSoLuong(), khuyenMai.getNgayBatDau(), khuyenMai.getNgayKetThuc()};
            model.addRow(row);
            return true; // Search successful
        } else {
            return false; // Search unsuccessful
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
       // Lấy thông tin từ các trường nhập liệu
    String phanTramGiam = txtphantramgiam.getText();
    String soLuong = txtsoluong.getText();
    Date ngayBatDau = ngaybatdau.getDate();
    Date ngayKetThuc = ngayketthuc.getDate();

    // Validate dữ liệu trước khi thêm
    if (!validateInput(phanTramGiam, soLuong, ngayBatDau, ngayKetThuc)) {
        return;
    }

    // Thêm mã khuyến mãi mới
    khuyenMaiService.themKhuyenMai(phanTramGiam, Integer.parseInt(soLuong), ngayBatDau, ngayKetThuc);

    // Load lại dữ liệu vào bảng
    loadDataToTable();

    // Thông báo thành công
    JOptionPane.showMessageDialog(this, "Thêm mã khuyến mãi thành công");
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        int selectedRow = tblKM.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một hàng để sửa");
            return;
        }

        // Lấy thông tin từ hàng đã chọn
        String maKM = tblKM.getValueAt(selectedRow, 0).toString();
        String phanTramGiamGia = txtphantramgiam.getText();
        int soLuong = Integer.parseInt(txtsoluong.getText());
        Date ngayBatDau = ngaybatdau.getDate();
        Date ngayKetThuc = ngayketthuc.getDate();

        // Cập nhật thông tin khuyến mãi
        khuyenMaiService.suaKhuyenMai(maKM, phanTramGiamGia, soLuong, ngayBatDau, ngayKetThuc);

        // Load lại dữ liệu vào bảng
        loadDataToTable();

        // Thông báo thành công
        JOptionPane.showMessageDialog(this, "Sửa thông tin khuyến mãi thành công");
    }//GEN-LAST:event_btnsuaActionPerformed

    private void tblKMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKMMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblKM.getSelectedRow();

        if (selectedRow != -1) {
            // Lấy thông tin từ hàng đã chọn
            String maKM = tblKM.getValueAt(selectedRow, 0).toString();
            String phanTramGiamGia = tblKM.getValueAt(selectedRow, 1).toString();
            String soLuong = tblKM.getValueAt(selectedRow, 2).toString();
            Date ngayBatDau = (Date) tblKM.getValueAt(selectedRow, 3);
            Date ngayKetThuc = (Date) tblKM.getValueAt(selectedRow, 4);

            // Hiển thị thông tin trong các trường trên giao diện
            txtphantramgiam.setText(phanTramGiamGia);
            txtsoluong.setText(soLuong);
            ngaybatdau.setDate(ngayBatDau);
            ngayketthuc.setDate(ngayKetThuc);
        }
    }//GEN-LAST:event_tblKMMouseClicked

    private void btnlammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlammoiActionPerformed
        // TODO add your handling code here:
        txtphantramgiam.setText("");
        txtsoluong.setText("");
        ngaybatdau.setDate(null);
        ngayketthuc.setDate(null);
        txtTimTheoma.setText("");
        loadDataToTable();
    }//GEN-LAST:event_btnlammoiActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblKM.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(KhuyenMaiPanell.this, "Vui lòng chọn một hàng để xóa");
            return;
        }

        // Lấy mã khuyến mãi từ hàng đã chọn
        String maKM = tblKM.getValueAt(selectedRow, 0).toString();

        // Xóa khuyến mãi từ cơ sở dữ liệu
        khuyenMaiService.xoaKhuyenMai(maKM);

        // Load lại dữ liệu vào bảng
        loadDataToTable();

        // Thông báo thành công
        JOptionPane.showMessageDialog(KhuyenMaiPanell.this, "Xóa khuyến mãi thành công");

    }//GEN-LAST:event_btnxoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnlammoi;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser ngaybatdau;
    private com.toedter.calendar.JDateChooser ngayketthuc;
    private javax.swing.JTable tblKM;
    private javax.swing.JTextField txtTimTheoma;
    private javax.swing.JTextField txtphantramgiam;
    private javax.swing.JTextField txtsoluong;
    // End of variables declaration//GEN-END:variables
}
